version: '3'
services:
  graph-drawer:
    build:
      context: app/
      args:
        - UID=${UID}
    volumes:
      - type: bind
        source: ./app
        target: /app
    expose:
      - 8000
    user: "${UID}:${UID}"
  
  nginx:
    image: nginx:1.21.3-alpine
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - graph-drawer
  
  sample_data:
    build:
      context: sample_data/
      args:
        - UID=${UID}
    volumes:
      - type: bind
        source: ./sample_data
        target: /sample_data
    user: "${UID}:${UID}"
    tty: true
